customer_list:
  path: /api/v1/customers
  controller: App\Controller\CustomerController:indexAction
  methods: [GET]

customer_create:
  path: /api/v1/customers
  controller: App\Controller\CustomerController:createAction
  methods: [POST]